server:
  port: ${PORT:8080}

app:
  title: Hello Application
  version: 1.0

summer:
  datasource:
    url: jdbc:mysql://10.10.102.83:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: buynow
    password: buynow
